<?php

namespace Muni\ConsejoBundle\Entity\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoRepository extends EntityRepository
{
}
