<?php

namespace Muni\ConsejoBundle\Entity\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * ResolucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResolucionRepository extends EntityRepository
{
    
    public function getResoluciones($busqueda)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('r')
            ->from('ConsejoBundle:Resolucion', 'r')
            ->where('r.resolucion LIKE :busqueda
                    OR r.descripcion LIKE :busqueda')
            ->setParameter('busqueda', "%{$busqueda}%")
            ->getQuery();
        return $query->getResult();
    }
}
